name: deppie
description: "A local AI chatbot assistant powered by the DeepSeek model."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/logo_lockup_flutter_vertical.png

  color_dark: "#042a49"
  image_dark: assets/logo_lockup_flutter_vertical_wht.png

  android_12:
    image: assets/android12splash.png
    color: "#42a5f5"
    icon_background_color: "#eeeeee"
